---
# Add or delete network object in Check Point management server
- name: add-network or delete-network
  check_point.mgmt.cp_mgmt_network:
    state: "{{item.state}}"
    color: "{{item.color}}"
#    groups: "{{item.groups}}"
    name: "{{item.name}}"
    subnet: "{{ item.subnet | ipaddr('network') }}"
    subnet_mask: "{{ item.subnet | ipaddr('netmask') }}"
  loop: "{{cp_mgmt_network_vars}}"
  notify: Publish and install handler
