---
    - name:  Create web server for sales
      cp_mgmt_host:
        name: "Sales Web Server"
        ip_address: 10.4.0.131
        color: red
      notify: Publish Handeler

    - name:  Create web server for development 
      cp_mgmt_host:
        name: "Dev Web Server"
        ip_address: 10.1.0.132
        color: orange
      notify: Publish Handeler
        
    - name: add-security-zone
      cp_mgmt_security_zone:
        color: blue 
        name: InsideZone 
        state: present
      notify: Publish Handeler

#    - set_fact:
#        eth1_ip: '{{ mem1_eth1_ip + "/" + mem1_eth1_length }}'
#
#    - set_fact:
#        eth1_network: "{{ eth1_ip | ipaddr('network') }}"

    - name:  Create Internal Network 
      cp_mgmt_network:
        name: "Internal_Network"
#        subnet: "{{ eth1_network }}"
        subnet: 1.1.1.0
#        mask_length: "{{ mem1_eth1_length }}"
        mask_length: 24
        state: present
        color: orange
        nat_settings:
           auto_rule: true
           hide_behind: "gateway"
           method: "hide"
      notify: Publish Handeler

    - name:  Create Jump Network
      cp_mgmt_network:
        name: "Jump_Network"
        subnet: "10.2.0.0"
        mask_length: "24"
        state: present
        color: orange
      notify: Publish Handeler

    - set_fact:
        policy_name: test_pol

    - name: Create Policy Package 
      cp_mgmt_package:
        access: true
        threat_prevention: true 
        color: blue
        name: "{{ policy_name }}" 
        state: present
      notify: Publish Handeler

    - name: "Set Threat Rule 1"
      cp_mgmt_threat_rule:
        layer: "{{ policy_name }} Threat Prevention" 
        name: "Threat Rule 1"
        position: "1"
#        action: "CPX_Threat_Profile"
      notify: Publish Handeler

    - name: Set Access Layer for URLF and APPC
      cp_mgmt_access_layer:
        applications_and_url_filtering: true 
        firewall: true
        name: "{{ policy_name }} Network" 
        state: present
      notify: Publish Handeler

    - name: Set Logging on the Cleanup rule 
      cp_mgmt_access_rule:
        layer: "{{ policy_name }} Network" 
        name: "Cleanup rule"
        track:
          type: "Log"
        state: present
      notify: Publish Handeler

    - name: Create rule - DHCP Rule
      cp_mgmt_access_rule:
        layer: "{{ policy_name }} Network"
        name: "DHCP Rules"
        position: "1"
        source:
          - InsideZone
        service:
          - dhcp
          - dhcp-relay 
        track:
          type: "Extended Log"
        action: Accept
      notify: Publish Handeler

    - name: Create rule - Demo Rule 
      cp_mgmt_access_rule:
        layer: "{{ policy_name }} Network"
        name: "Demo WebServer Rule"
        position: "2"
        source:
                - "Sales Web Server"
#                - "cpx2020-vm (cpx2020-resources)"
        destination:
          - "Dev Web Server"
        service:
          - https
          - http
          - ftp  
        track:
          type: "Extended Log"         
        action: Accept
        source_negate: no 
      notify: Publish Handeler

    - name: Create rule - SSH 
      cp_mgmt_access_rule:
        layer: "{{ policy_name }} Network"
        name: "Gaia API and SSH Access"
        position: "3"
        source: "Jump_Network"
        service:
          - ssh
          - icmp-requests
          - https
          - dns
          - http
        track:
          type: "Extended Log"
        action: Drop
      notify: Publish Handeler

    - name: Internal to Internet 
      cp_mgmt_access_rule:
        layer: "{{ policy_name }} Network"
        name: "Internal to Internet"
        position: "4"
        source: "Internal_Network"
        track:
          type: "Extended Log"
        action: Drop
      notify: Publish Handeler 
